// <auto-generated />
using System;
using CSGOStats.Services.MatchStatisticsParse.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CSGOStats.Services.MatchStatisticsParse.Data.EF.Migrations
{
    [DbContext(typeof(MigrationsDataContext))]
    [Migration("20200201195641_ReplacedIsProcessedPropertyWithDateTimeValues")]
    partial class ReplacedIsProcessedPropertyWithDateTimeValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CSGOStats.Services.MatchStatisticsParse.Data.Entities.ScheduledGameParse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("2020-02-01T19:56:41.2912604Z (ISO)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ProcessedAt")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScheduledGameParse","MatchStatisticsParse");
                });

            modelBuilder.Entity("CSGOStats.Services.MatchStatisticsParse.Data.Entities.ScheduledMapParse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("2020-02-01T19:56:41.3068314Z (ISO)");

                    b.Property<Guid?>("GameId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ProcessedAt")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScheduledMapParse","MatchStatisticsParse");
                });
#pragma warning restore 612, 618
        }
    }
}
