// <auto-generated />
using System;
using CSGOStats.Services.MatchStatisticsParse.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CSGOStats.Services.MatchStatisticsParse.Data.EF.Migrations
{
    [DbContext(typeof(MigrationsDataContext))]
    [Migration("20200103172442_AddIsProcessedFlagToScheduledMapParse")]
    partial class AddIsProcessedFlagToScheduledMapParse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CSGOStats.Services.MatchStatisticsParse.Data.Entities.ScheduledGameParse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ScheduledGameParse","MatchStatisticsParse");
                });

            modelBuilder.Entity("CSGOStats.Services.MatchStatisticsParse.Data.Entities.ScheduledMapParse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ScheduledMapParse","MatchStatisticsParse");
                });
#pragma warning restore 612, 618
        }
    }
}
